# Site settings
title: Ashley Ellis
email: anellis12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog and landing page of Ashley Ellis, Ruby developer.
baseurl:   # the subpath of your site, e.g. /blog/
url: "http://ashleyellis.io" # the base hostname & protocol for your site
twitter_username: ashleynellis
github_username:  anellis

# Build settings
markdown: kramdown
